//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class masterEntities1 : DbContext
    {
        public masterEntities1()
            : base("name=masterEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<Seller> Sellers { get; set; }
        public virtual DbSet<MSreplication_options> MSreplication_options { get; set; }
        public virtual DbSet<spt_fallback_db> spt_fallback_db { get; set; }
        public virtual DbSet<spt_fallback_dev> spt_fallback_dev { get; set; }
        public virtual DbSet<spt_fallback_usg> spt_fallback_usg { get; set; }
        public virtual DbSet<spt_monitor> spt_monitor { get; set; }
    
        public virtual int sp_MScleanupmergepublisher()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MScleanupmergepublisher");
        }
    
        public virtual int sp_MSrepl_startup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSrepl_startup");
        }
    
        public virtual int InsertInformation(string product, Nullable<System.DateTime> startDeliveryDate, Nullable<System.DateTime> endDeliveryDate)
        {
            var productParameter = product != null ?
                new ObjectParameter("Product", product) :
                new ObjectParameter("Product", typeof(string));
    
            var startDeliveryDateParameter = startDeliveryDate.HasValue ?
                new ObjectParameter("StartDeliveryDate", startDeliveryDate) :
                new ObjectParameter("StartDeliveryDate", typeof(System.DateTime));
    
            var endDeliveryDateParameter = endDeliveryDate.HasValue ?
                new ObjectParameter("EndDeliveryDate", endDeliveryDate) :
                new ObjectParameter("EndDeliveryDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertInformation", productParameter, startDeliveryDateParameter, endDeliveryDateParameter);
        }
    
        public virtual int InsertSeller(string sellerName, string country, string product)
        {
            var sellerNameParameter = sellerName != null ?
                new ObjectParameter("SellerName", sellerName) :
                new ObjectParameter("SellerName", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var productParameter = product != null ?
                new ObjectParameter("Product", product) :
                new ObjectParameter("Product", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertSeller", sellerNameParameter, countryParameter, productParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ValidateInformation(string product, Nullable<System.DateTime> startDeliveryDate, Nullable<System.DateTime> endDeliveryDate)
        {
            var productParameter = product != null ?
                new ObjectParameter("Product", product) :
                new ObjectParameter("Product", typeof(string));
    
            var startDeliveryDateParameter = startDeliveryDate.HasValue ?
                new ObjectParameter("StartDeliveryDate", startDeliveryDate) :
                new ObjectParameter("StartDeliveryDate", typeof(System.DateTime));
    
            var endDeliveryDateParameter = endDeliveryDate.HasValue ?
                new ObjectParameter("EndDeliveryDate", endDeliveryDate) :
                new ObjectParameter("EndDeliveryDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ValidateInformation", productParameter, startDeliveryDateParameter, endDeliveryDateParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ValidateSeller(string sellerName, string country, string product)
        {
            var sellerNameParameter = sellerName != null ?
                new ObjectParameter("SellerName", sellerName) :
                new ObjectParameter("SellerName", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var productParameter = product != null ?
                new ObjectParameter("Product", product) :
                new ObjectParameter("Product", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ValidateSeller", sellerNameParameter, countryParameter, productParameter);
        }
    
        public virtual ObjectResult<Display_Result> Display()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Display_Result>("Display");
        }
    }
}
