//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Seller
    {
        public int No { get; set; }
        [Display(Name = " Seller Name ")]
        public string SellerName { get; set; }
        [Display(Name = "Country")]

        public string Country { get; set; }
        [Display(Name = "Product Name")]

        public string Product { get; set; }
    }
}
